driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true  # Ensure deprecated features fail early

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      box: centos/7
  - name: ubuntu-20.04  # Ubuntu Focal (LTS)
    driver:
      box: ubuntu/focal64
  - name: debian-11  # Debian Bullseye
    driver:
      box: debian/bullseye

suites:
  - name: config
    run_list:
      - recipe[default]
    attributes: {}
